### ISSUE TITLE
Cache - picture upload

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [upframe/upframe.io#128]
<img width="960" alt="000011" src="https://user-images.githubusercontent.com/42959314/52149585-8075b800-266d-11e9-84c6-16d8b3c981c2.png">

- shows pic only after manual cache reload
@ulissesferreira 
@fabiofcferreira

**Comment by ulissesferreira** [comment]
Probably related to #111 I've telling y'all that's important because by fixing that you basically enforce a pattern that fixes a lot of inconsistencies. Tomorrow I will take a look when I can.

**Comment by fabiofcferreira** [comment]
This could be related to #111 even though it is not directly related. What's causing that issue is the fact that the profile picture URL is sent on mentor profile info fetch request, which means, every time you change your picture you also have to update your mentor info.

This would be solved either by sending one info fetch request after the profile picture upload or by returning the link for the file in the upload request. But due to its simplicity, I guess the first option is the best.

**Comment by SwenSchaeferjohann** [comment]
> But due to its simplicity, I guess the first option is the best.

How simple? lot of work?
