### ISSUE TITLE
The hover in the Primary Button is not working properly

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#238]
![image](https://user-images.githubusercontent.com/6923650/76317488-8f9d4f80-62dc-11ea-9923-515f2e735aac.png)

For some guidance on how to implement the right hover properties, please check Courtyard, our design guide at Figma.

**Comment by malikpiara** [comment]
https://files.slack.com/files-pri/T0QJAAGUE-FV4591SNR/2020-03-09_23.02.46.gif

**Comment by Samson303** [comment]
Works Locally but will investigate further why this happens on staging

**Comment by MathisBullinger** [comment]
The build process that CRA uses to create the bundle, [incorrectly transforms](https://github.com/facebook/create-react-app/issues/7980) any percentage value assigned to the opacity property to `1%`.

<img width="1074" alt="Screenshot 2020-03-14 at 14 33 45" src="https://user-images.githubusercontent.com/26855066/76683090-904a2480-6601-11ea-9a31-ea5967ef5c56.png">

@Samson303 The opacity should be specified as a number between 0 and 1 (i.e. `opacity: 0.7;`) because not all browsers [support percentage opacity values](https://caniuse.com/#feat=mdn-css_properties_opacity_percentages).

**Comment by Samson303** [comment]
Ok thats why it works locally and not when pushed. I will change all of the instances of opacity to 0-1 now and commit them
